### ISSUE TITLE
First time install issues

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express-starter#10]
When trying to run the multi-site environment for the first time I got a lot of php warnings and sites were not building properly.

`jeor0980@OSR-WEB-L-006:~/Documents/Work/lando/multi-site$ lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting express_database_1 ... 
Recreating express_appserver_1 ... 
Starting express_database_1
Recreating express_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0   1894      0 --:--:-- --:--:-- --:--:--  1895
100 5912k  100 5912k    0     0  4097k      0  0:00:01  0:00:01 --:--:-- 15.5M
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20160303/opcache.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20160303/opcache.so: undefined symbol: zend_signal_globals
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so: undefined symbol: zend_pass_function
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/apcu.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/bcmath.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/bcmath.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/bz2.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/bz2.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/calendar.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/calendar.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/exif.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/exif.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gd.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gd.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gettext.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gettext.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/imagick.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/imagick.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/imap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/imap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/intl.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/intl.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/ldap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/ldap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mcrypt.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mcrypt.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/memcached.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/memcached.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysqli.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/oauth.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/oauth.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_pgsql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/redis.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/soap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/soap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/zip.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/zip.so: cannot open shared object file: No such file or directory in Unknown on line 0`

@kevincrafts reported a similar experience. My easy "fix" was to change the php version to 7.0 instead of 7.1 in the .lando.yml file. 

To get lando to work properly with php 7.1 I did a couple of things but I'm not specifically sure what was

- [Updated lando to the latest version](https://docs.devwithlando.io/installation/installing.html)
- Re-installed PHP with homebrew

**Comment by alexfinnarn** [comment]
@jeor0980 is this still an issue? If not, please close.
