### ISSUE TITLE
Remove Lando Abstraction Layer

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express-starter#13]
As more customizations happen, errors/bugs are reported, it is becoming a PITA to work through the abstraction layer that Lando adds to Docker Compose. It is also annoying to get RTFM'd when the linked docs don't work or aren't as magical as the core devs think they are...yes, you do have docs, I can read...

While Lando might be great for trying a lot of different dev stacks, Express only needs a LAMP stack and a few Docker images. Everything else Lando adds on top of that potentially interferes with the setup, and I'm already customizing all parts of the LAMP stack.

**Comment by kreynen** [comment]
Before you go too far down this road, take a look at https://github.com/rancher/rancher/wiki/Cowpoke-1:-Getting-Started-with-Rancher.  The instructions are for spinning up containers with Python on OSX, but it is quick way to start digging into Rancher.

**Comment by alexfinnarn** [comment]
I was going to ask about Rancher. I don't know much about Docker or Docker Compose but that's kind of the point of this exercise.

http://rancher.com/docs/rancher/latest/en/cattle/rancher-compose/ might be helpful.

**Comment by alexfinnarn** [comment]
Rancher seems way complicated when only considering a local development environment. https://docs.docker.com/samples/library/drupal/ seems like a more reasonable place to start.

**Comment by alexfinnarn** [comment]
I just made a "lando" branch to archive that version.
