### ISSUE TITLE
Add option for checking out CU drupal-7.x in build-express.sh

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express-starter#6]

**Comment by alexfinnarn** [comment]
While it is a good idea to prevent users from entering "wrong" choices and not getting any feedback from that, I went ahead and added defaults in the `scripts/build-code` script. The user has to configure that file anyway and can hardcode what they want. 

When creating a site via `lando create-site`, the user is prompted for installation options and can't enter a "bad" value.
